spring:
  application:
    name: service-desk

  datasource:
    url: jdbc:postgresql://localhost:5432/service_desk_db
    username: malik
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


jwt:
  # For production set JWT_SECRET env. Default value below is HEX-encoded 32-byte key.
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  secret-encoding: ${JWT_SECRET_ENCODING:hex}
  expiration: ${JWT_EXPIRATION:900000} # 15 minutes in milliseconds
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days in milliseconds
